name: Build & Test

on:
  push:
    branches-ignore:
      - "master"
      - "maintenance/v*"
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  checks: write
  pull-requests: write


jobs:
  build-and-test:
    name: Build and Test (Solr ${{matrix.solr}} / Java${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 11, 8 ]
        solr: [ 8.11.1, 7.7.3,  6.6.6 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up Java/Maven
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Compile & Test
        env:
          SOLR_VERSION: ${{ matrix.solr }}
        run: mvn -V -B --no-transfer-progress
          clean package verify
          -Prelease
          -Dgpg.skip
          -Dsolr.version=${SOLR_VERSION}
      - name: Upload Test-Results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Test Results (${{matrix.solr}} - Java${{ matrix.java }})
          path: '**/TEST-*.xml'

  publish-test-results:
    name: Publish Test Results
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Fetch Test-Results
        uses: actions/download-artifact@v3
        with:
          path: test-results
      - name: Publish Test-Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: 'test-results/**/TEST-*.xml'
