name: Build & Test

on:
  push:
    branches-ignore:
      - "main"
      - "maintenance/v*"
  pull_request:
    types: [ opened, synchronize, reopened ]

permissions:
  checks: write
  pull-requests: write


jobs:
  build-and-test:
    name: Build and Test (Lucene ${{matrix.lucene}} / Java${{ matrix.java }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        java: [ 21, 17, 11 ]
        lucene: [ 9.10.0, 9.1.0 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0
        with:
          fetch-depth: 0
      - name: Set up Java/Maven
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'
          cache: maven
      - name: Compile & Test
        env:
          LUCENE_VERSION: ${{ matrix.lucene }}
        run: ./mvnw -V -B --no-transfer-progress
          clean verify
          -Prelease
          -Dgpg.skip
          -Dlucene.version=${LUCENE_VERSION}
      - name: Upload Test-Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Test Results (${{matrix.lucene}} - Java${{ matrix.java }})
          path: '**/TEST-*.xml'

  publish-test-results:
    name: Publish Test Results
    needs: [ build-and-test ]
    runs-on: ubuntu-latest
    if: always()

    steps:
      - name: Fetch Test-Results
        uses: actions/download-artifact@v4
        with:
          path: test-results
      - name: Publish Test-Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          files: 'test-results/**/TEST-*.xml'
          action_fail_on_inconclusive: 'true'
